<!--
    ChatbotWidget.vue
    Auto-generated by FutureCloud CLI
    ─────────────────────────────────────────────────────────────────
    Cara penggunaan:
      import ChatbotWidget from './src/components/ChatbotWidget.vue';
      // Lalu tambahkan <ChatbotWidget /> di App.vue
    ─────────────────────────────────────────────────────────────────
-->

<template>
  <div id="fc-chatbot-widget">
    <!-- Chat Window -->
    <transition name="fc-slide">
      <div v-if="isOpen" id="fc-chat-window">
        <div id="fc-chat-header">
          <span>Customer Support</span>
          <button id="fc-chat-close" @click="isOpen = false">✖</button>
        </div>
        <div id="fc-chat-body" ref="chatBody">
          <div
            v-for="(msg, index) in messages"
            :key="index"
            :class="['fc-msg', msg.sender === 'user' ? 'fc-msg-user' : 'fc-msg-bot']"
          >
            {{ msg.text }}
          </div>
        </div>
        <div id="fc-chat-input-container">
          <input
            v-model="userInput"
            type="text"
            id="fc-chat-input"
            placeholder="Ketik pesan..."
            @keypress.enter="sendMessage"
          />
          <button id="fc-chat-submit" @click="sendMessage">Kirim</button>
        </div>
      </div>
    </transition>

    <!-- Toggle Button -->
    <button id="fc-chat-btn" @click="isOpen = !isOpen">💬</button>
  </div>
</template>

<script>
// ┌─ KUSTOMISASI ─────────────────────────────────────────────────┐
// │ Ganti dengan import dari env jika diperlukan:                 │
// │   const LICENSE_KEY = process.env.VUE_APP_FUTURECLOUD_KEY;   │
// └──────────────────────────────────────────────────────────────┘
const LICENSE_KEY = '__LICENSE_KEY__';
const API_URL     = '__API_URL__';

export default {
  name: 'ChatbotWidget',

  data() {
    return {
      isOpen: false,
      userInput: '',
      messages: [{ text: 'Halo! Ada yang bisa kami bantu?', sender: 'bot' }],
      sessionId: localStorage.getItem('fc_chat_session') || this.generateSessionId(),
    };
  },

  methods: {
    generateSessionId() {
      const id = 'fc_' + Math.random().toString(36).substr(2, 9);
      localStorage.setItem('fc_chat_session', id);
      return id;
    },

    appendMessage(text, sender) {
      this.messages.push({ text, sender });
      this.$nextTick(() => {
        if (this.$refs.chatBody) {
          this.$refs.chatBody.scrollTop = this.$refs.chatBody.scrollHeight;
        }
      });
    },

    async sendMessage() {
      const text = this.userInput.trim();
      if (!text) return;

      this.appendMessage(text, 'user');
      this.userInput = '';

      try {
        const res = await fetch(`${API_URL}/chat/send`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-FutureCloud-License': LICENSE_KEY,
          },
          body: JSON.stringify({ message: text, session_id: this.sessionId }),
        });

        const data = await res.json();

        if (data.reply) this.appendMessage(data.reply, 'bot');
        else if (data.error) this.appendMessage('Error: ' + data.error, 'bot');
      } catch {
        this.appendMessage('Gagal terhubung ke server.', 'bot');
      }
    },
  },
};
</script>

<style scoped>
#fc-chatbot-widget {
  position: fixed;
  bottom: 20px;
  right: 20px;
  z-index: 999999;
  font-family: system-ui, -apple-system, sans-serif;
}

#fc-chat-btn {
  background: #14b8a6;
  color: white;
  border: none;
  width: 60px;
  height: 60px;
  border-radius: 50%;
  cursor: pointer;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  font-size: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
}

#fc-chat-window {
  width: 350px;
  height: 500px;
  background: white;
  border-radius: 12px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15);
  display: flex;
  flex-direction: column;
  overflow: hidden;
  margin-bottom: 15px;
  border: 1px solid #e2e8f0;
}

#fc-chat-header {
  background: #14b8a6;
  color: white;
  padding: 15px;
  font-weight: bold;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

#fc-chat-close {
  background: none;
  border: none;
  color: white;
  cursor: pointer;
  font-size: 16px;
}

#fc-chat-body {
  flex: 1;
  padding: 15px;
  overflow-y: auto;
  background: #f8fafc;
}

#fc-chat-input-container {
  display: flex;
  padding: 10px;
  border-top: 1px solid #e2e8f0;
  background: white;
}

#fc-chat-input {
  flex: 1;
  padding: 10px;
  border: 1px solid #cbd5e1;
  border-radius: 6px;
  outline: none;
}

#fc-chat-submit {
  background: #14b8a6;
  color: white;
  border: none;
  padding: 0 15px;
  margin-left: 10px;
  border-radius: 6px;
  cursor: pointer;
}

.fc-msg {
  margin-bottom: 10px;
  max-width: 80%;
  padding: 10px 14px;
  border-radius: 12px;
  font-size: 14px;
  line-height: 1.4;
}

.fc-msg-user {
  background: #14b8a6;
  color: white;
  margin-left: auto;
  border-bottom-right-radius: 4px;
}

.fc-msg-bot {
  background: #e2e8f0;
  color: #1e293b;
  margin-right: auto;
  border-bottom-left-radius: 4px;
}

/* Animasi slide-up untuk chat window */
.fc-slide-enter-active,
.fc-slide-leave-active {
  transition: all 0.2s ease;
}
.fc-slide-enter-from,
.fc-slide-leave-to {
  opacity: 0;
  transform: translateY(10px);
}
</style>
