/**
 * FutureCloud Chatbot UI
 * Auto-generated by FutureCloud CLI
 */

(function() {
    const LICENSE_KEY = '__LICENSE_KEY__';
    const API_URL = '__API_URL__';
    let sessionId = localStorage.getItem('fc_chat_session') || ('fc_' + Math.random().toString(36).substr(2, 9));
    localStorage.setItem('fc_chat_session', sessionId);

    // 1. Inject Styles
    const style = document.createElement('style');
    style.innerHTML = `
        #fc-chatbot-widget {
            position: fixed; bottom: 20px; right: 20px; z-index: 999999;
            font-family: system-ui, -apple-system, sans-serif;
        }
        #fc-chat-btn {
            background: #14b8a6; color: white; border: none;
            width: 60px; height: 60px; border-radius: 50%;
            cursor: pointer; box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            font-size: 24px; display: flex; align-items: center; justify-content: center;
        }
        #fc-chat-window {
            display: none; width: 350px; height: 500px;
            background: white; border-radius: 12px;
            box-shadow: 0 8px 24px rgba(0,0,0,0.15);
            flex-direction: column; overflow: hidden;
            margin-bottom: 15px; border: 1px solid #e2e8f0;
        }
        #fc-chat-header {
            background: #14b8a6; color: white; padding: 15px;
            font-weight: bold; display: flex; justify-content: space-between;
        }
        #fc-chat-close { background: none; border: none; color: white; cursor: pointer; font-size: 16px; }
        #fc-chat-body { flex: 1; padding: 15px; overflow-y: auto; background: #f8fafc; }
        #fc-chat-input-container { display: flex; padding: 10px; border-top: 1px solid #e2e8f0; background: white; }
        #fc-chat-input { flex: 1; padding: 10px; border: 1px solid #cbd5e1; border-radius: 6px; outline: none; }
        #fc-chat-submit { background: #14b8a6; color: white; border: none; padding: 0 15px; margin-left: 10px; border-radius: 6px; cursor: pointer; }
        
        .fc-msg { margin-bottom: 10px; max-width: 80%; padding: 10px 14px; border-radius: 12px; font-size: 14px; line-height: 1.4; }
        .fc-msg-user { background: #14b8a6; color: white; margin-left: auto; border-bottom-right-radius: 4px; }
        .fc-msg-bot { background: #e2e8f0; color: #1e293b; margin-right: auto; border-bottom-left-radius: 4px; }
    `;
    document.head.appendChild(style);

    // 2. Inject HTML elements
    const widgetContainer = document.createElement('div');
    widgetContainer.id = 'fc-chatbot-widget';
    widgetContainer.innerHTML = `
        <div id="fc-chat-window">
            <div id="fc-chat-header">
                <span>Customer Support</span>
                <button id="fc-chat-close">✖</button>
            </div>
            <div id="fc-chat-body">
                <div class="fc-msg fc-msg-bot">Halo! Ada yang bisa kami bantu?</div>
            </div>
            <div id="fc-chat-input-container">
                <input type="text" id="fc-chat-input" placeholder="Ketik pesan..." />
                <button id="fc-chat-submit">Kirim</button>
            </div>
        </div>
        <button id="fc-chat-btn">💬</button>
    `;
    document.body.appendChild(widgetContainer);

    // 3. Logic & Event Listeners
    const chatBtn = document.getElementById('fc-chat-btn');
    const chatWindow = document.getElementById('fc-chat-window');
    const chatClose = document.getElementById('fc-chat-close');
    const chatInput = document.getElementById('fc-chat-input');
    const chatSubmit = document.getElementById('fc-chat-submit');
    const chatBody = document.getElementById('fc-chat-body');

    chatBtn.addEventListener('click', () => {
        chatWindow.style.display = chatWindow.style.display === 'flex' ? 'none' : 'flex';
    });

    chatClose.addEventListener('click', () => {
        chatWindow.style.display = 'none';
    });

    function appendMessage(text, sender) {
        const msgDiv = document.createElement('div');
        msgDiv.className = \`fc-msg fc-msg-\${sender}\`;
        msgDiv.innerText = text;
        chatBody.appendChild(msgDiv);
        chatBody.scrollTop = chatBody.scrollHeight;
    }

    async function sendMessage() {
        const text = chatInput.value.trim();
        if (!text) return;
        
        appendMessage(text, 'user');
        chatInput.value = '';

        try {
            const res = await fetch(\`\${API_URL}/chat/send\`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-FutureCloud-License': LICENSE_KEY
                },
                body: JSON.stringify({ message: text, session_id: sessionId })
            });
            const data = await res.json();
            
            if (data.reply) {
                appendMessage(data.reply, 'bot');
            } else if (data.error) {
                appendMessage("Error: " + data.error, 'bot');
            }
        } catch (e) {
            appendMessage("Gagal terhubung ke server.", 'bot');
        }
    }

    chatSubmit.addEventListener('click', sendMessage);
    chatInput.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') sendMessage();
    });
})();
