/**
 * chatbot-component.jsx
 * Auto-generated by FutureCloud CLI
 * ─────────────────────────────────────────────────────────────────
 * Cara penggunaan:
 *   import FutureCloudChatbot from './src/components/FutureCloudChatbot';
 *   // Lalu tambahkan <FutureCloudChatbot /> di App.jsx atau layout
 * ─────────────────────────────────────────────────────────────────
 */

import React, { useState, useRef, useEffect } from 'react';

// ┌─ KUSTOMISASI ─────────────────────────────────────────────────┐
// │ Ganti LICENSE_KEY dan API_URL jika perlu override dari env.   │
// │ Atau baca dari: process.env.REACT_APP_FUTURECLOUD_KEY         │
// └──────────────────────────────────────────────────────────────┘
const LICENSE_KEY = '__LICENSE_KEY__';
const API_URL     = '__API_URL__';

const styles = {
  widget: {
    position: 'fixed', bottom: '20px', right: '20px', zIndex: 999999,
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  btn: {
    background: '#14b8a6', color: 'white', border: 'none',
    width: '60px', height: '60px', borderRadius: '50%',
    cursor: 'pointer', boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    fontSize: '24px', display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  window: {
    width: '350px', height: '500px', background: 'white',
    borderRadius: '12px', boxShadow: '0 8px 24px rgba(0,0,0,0.15)',
    display: 'flex', flexDirection: 'column', overflow: 'hidden',
    marginBottom: '15px', border: '1px solid #e2e8f0',
  },
  header: {
    background: '#14b8a6', color: 'white', padding: '15px',
    fontWeight: 'bold', display: 'flex', justifyContent: 'space-between', alignItems: 'center',
  },
  closeBtn: { background: 'none', border: 'none', color: 'white', cursor: 'pointer', fontSize: '16px' },
  body: { flex: 1, padding: '15px', overflowY: 'auto', background: '#f8fafc' },
  inputContainer: { display: 'flex', padding: '10px', borderTop: '1px solid #e2e8f0', background: 'white' },
  input: { flex: 1, padding: '10px', border: '1px solid #cbd5e1', borderRadius: '6px', outline: 'none' },
  submitBtn: { background: '#14b8a6', color: 'white', border: 'none', padding: '0 15px', marginLeft: '10px', borderRadius: '6px', cursor: 'pointer' },
};

export default function FutureCloudChatbot() {
  const [isOpen, setIsOpen]     = useState(false);
  const [messages, setMessages] = useState([{ text: 'Halo! Ada yang bisa kami bantu?', sender: 'bot' }]);
  const [input, setInput]       = useState('');
  const bodyRef = useRef(null);

  // Ambil atau buat session ID
  const sessionId = useRef(
    localStorage.getItem('fc_chat_session') || (() => {
      const id = 'fc_' + Math.random().toString(36).substr(2, 9);
      localStorage.setItem('fc_chat_session', id);
      return id;
    })()
  ).current;

  // Auto-scroll ke bawah setiap ada pesan baru
  useEffect(() => {
    if (bodyRef.current) {
      bodyRef.current.scrollTop = bodyRef.current.scrollHeight;
    }
  }, [messages]);

  const appendMessage = (text, sender) =>
    setMessages((prev) => [...prev, { text, sender }]);

  const sendMessage = async () => {
    const text = input.trim();
    if (!text) return;

    appendMessage(text, 'user');
    setInput('');

    try {
      const res = await fetch(`${API_URL}/chat/send`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-FutureCloud-License': LICENSE_KEY,
        },
        body: JSON.stringify({ message: text, session_id: sessionId }),
      });
      const data = await res.json();

      if (data.reply) appendMessage(data.reply, 'bot');
      else if (data.error) appendMessage('Error: ' + data.error, 'bot');
    } catch {
      appendMessage('Gagal terhubung ke server.', 'bot');
    }
  };

  const handleKeyPress = (e) => { if (e.key === 'Enter') sendMessage(); };

  return (
    <div style={styles.widget}>
      {isOpen && (
        <div style={styles.window}>
          <div style={styles.header}>
            <span>Customer Support</span>
            <button style={styles.closeBtn} onClick={() => setIsOpen(false)}>✖</button>
          </div>
          <div style={styles.body} ref={bodyRef}>
            {messages.map((msg, i) => (
              <div
                key={i}
                style={{
                  marginBottom: '10px', maxWidth: '80%', padding: '10px 14px',
                  borderRadius: '12px', fontSize: '14px', lineHeight: '1.4',
                  background: msg.sender === 'user' ? '#14b8a6' : '#e2e8f0',
                  color: msg.sender === 'user' ? 'white' : '#1e293b',
                  marginLeft: msg.sender === 'user' ? 'auto' : undefined,
                  borderBottomRightRadius: msg.sender === 'user' ? '4px' : undefined,
                  borderBottomLeftRadius: msg.sender === 'bot' ? '4px' : undefined,
                }}
              >
                {msg.text}
              </div>
            ))}
          </div>
          <div style={styles.inputContainer}>
            <input
              style={styles.input}
              type="text"
              placeholder="Ketik pesan..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyPress={handleKeyPress}
            />
            <button style={styles.submitBtn} onClick={sendMessage}>Kirim</button>
          </div>
        </div>
      )}
      <button style={styles.btn} onClick={() => setIsOpen((o) => !o)}>💬</button>
    </div>
  );
}
